"""
style_packs.py — Pre-configured journal/submission-style presets.
Each value is a partial state dict that can be merged over the current config.
"""

from typing import Dict, Any

STYLE_PACKS: Dict[str, Dict[str, Any]] = {
    "JBL (Journal of Biblical Literature)": {
        "cit_style": "SBL",
        "biblatex_style": "verbose-note",
        "font_size": "11pt",
        "paper": "letterpaper",
        "margin": "1.0",
        "linespace": "2",
        "parindent": "0.5",
        "notes_mode": "footnote",
    },
    "NTS (New Testament Studies)": {
        "cit_style": "SBL",
        "biblatex_style": "verbose-note",
        "font_size": "12pt",
        "paper": "a4paper",
        "margin": "1.18",
        "linespace": "2",
        "parindent": "0.5",
        "notes_mode": "footnote",
    },
    "CBQ (Catholic Biblical Quarterly)": {
        "cit_style": "SBL",
        "biblatex_style": "verbose-note",
        "font_size": "12pt",
        "paper": "letterpaper",
        "margin": "1.0",
        "linespace": "2",
        "parindent": "0.5",
        "notes_mode": "footnote",
    },
    "HTR (Harvard Theological Review)": {
        "cit_style": "Chicago",
        "biblatex_style": "chicago-notes",
        "font_size": "11pt",
        "paper": "letterpaper",
        "margin": "1.25",
        "linespace": "2",
        "notes_mode": "footnote",
    },
    "JETS (Journal of the Evangelical Theological Society)": {
        "cit_style": "SBL",
        "biblatex_style": "verbose-note",
        "font_size": "12pt",
        "paper": "letterpaper",
        "margin": "1.0",
        "linespace": "2",
        "parindent": "0.5",
        "notes_mode": "footnote",
    },
    "Chicago 17th — Notes-Bibliography": {
        "cit_style": "Chicago",
        "biblatex_style": "chicago-notes",
        "font_size": "12pt",
        "paper": "letterpaper",
        "margin": "1.0",
        "linespace": "2",
        "parindent": "0.5",
        "notes_mode": "footnote",
    },
    "Chicago 17th — Author-Date": {
        "cit_style": "Chicago",
        "biblatex_style": "chicago-authordate",
        "font_size": "12pt",
        "paper": "letterpaper",
        "margin": "1.0",
        "linespace": "2",
        "notes_mode": "none",
    },
    "Turabian 9th (Student Paper)": {
        "cit_style": "Chicago",
        "biblatex_style": "chicago-notes",
        "font_size": "12pt",
        "paper": "letterpaper",
        "margin": "1.0",
        "linespace": "2",
        "parindent": "0.5",
        "notes_mode": "footnote",
        "has_abstract": False,
    },
    "APA 7th (Student Paper)": {
        "cit_style": "APA",
        "biblatex_style": "apa",
        "font_size": "12pt",
        "paper": "letterpaper",
        "margin": "1.0",
        "linespace": "2",
        "parindent": "0.5",
        "notes_mode": "none",
        "has_abstract": True,
        "has_keywords": True,
    },
    "MLA 9th (Humanities Paper)": {
        "cit_style": "MLA",
        "biblatex_style": "mla",
        "font_size": "12pt",
        "paper": "letterpaper",
        "margin": "1.0",
        "linespace": "2",
        "parindent": "0.5",
        "notes_mode": "none",
    },
}
